// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxlbklxSSOCyxOmMW2C5HWPc2msta1Kko',
    appId: '1:8746645603:web:684bc3ba6bbf512d32e056',
    messagingSenderId: '8746645603',
    projectId: 'courier-client-app',
    authDomain: 'courier-client-app.firebaseapp.com',
    storageBucket: 'courier-client-app.appspot.com',
    measurementId: 'G-HS2CEL1LKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2LgSDfbI_M13YkkiZ7QVXBS2QLIyuoQ',
    appId: '1:8746645603:android:86d3bd7c3716c83f32e056',
    messagingSenderId: '8746645603',
    projectId: 'courier-client-app',
    storageBucket: 'courier-client-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbDB_AkAMm7tSn-Hat7TDwYjjNBwhleDk',
    appId: '1:8746645603:ios:f7bc4cc1ed003e2032e056',
    messagingSenderId: '8746645603',
    projectId: 'courier-client-app',
    storageBucket: 'courier-client-app.appspot.com',
    androidClientId: '8746645603-7qbdi63dcd1a3nh6qsllutcqdqmq4gcv.apps.googleusercontent.com',
    iosClientId: '8746645603-gj0ro816o8orin4qirhr60k3ojbos7uj.apps.googleusercontent.com',
    iosBundleId: 'com.example.courierClientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbDB_AkAMm7tSn-Hat7TDwYjjNBwhleDk',
    appId: '1:8746645603:ios:8b1bbb1d5b1000e032e056',
    messagingSenderId: '8746645603',
    projectId: 'courier-client-app',
    storageBucket: 'courier-client-app.appspot.com',
    androidClientId: '8746645603-7qbdi63dcd1a3nh6qsllutcqdqmq4gcv.apps.googleusercontent.com',
    iosClientId: '8746645603-bfbn0sgptqs7f1f4rbjl1nrqqns6p4mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.courierClientApp.RunnerTests',
  );
}
